name: publish

on:
  push:
    branches: [ main ]

jobs:
  publish-tablerotorneo:
    name: "Buildear front y deployarla en el server"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Clonar este repository
        uses: actions/checkout@v3
      - name: Instalar NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Instalar paquetes
        run: npm install
      - name: Buildear App
        run: CI=false npm run build
      - name: Deployar
        uses: egnuez/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete -O --no-perms
          RSYNC_TARGET: /tmp/build
          RSYNC_SOURCE: /build/
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}
          SSH_USERNAME: ${{secrets.SSH_USERNAME}}
          SSH_HOSTNAME: ${{secrets.SSH_HOSTNAME}}
          SSH_PORT: ${{secrets.SSH_PORT}}
